### PR TITLE
fixed issues with profile and like/going functionality

### LINKED ISSUE #12: Set up event "like" functionality

### LINKED ISSUE #13: Set up event "going" functionality

### LINKED ISSUE #14: User can view/change their profile image in their profile view

### PR DESCRIPTION
**Pull request by shreyashekhar**
- Fixed problem so that image is saved to User object in Database when uploaded
- Fixed problems with going/like functionality on event detail view
- Fixed problem with profile page not displaying proper events
- Added color scheme + some design elements to app (incorporated some design advice from design session)
- Fixed problem with swipe reloading on profile page

### CODE REVIEW

File: app/src/main/java/com/example/solidarity/ProfileFragment.java [hunk 1]
```diff
@@ -53,17 +59,19 @@
...
 
 
     @Override
     public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
         super.onViewCreated(view, savedInstanceState);
         FrameLayout flayout = view.findViewById(R.id.fLayout);
-        profImage = new CircleImageView(getContext());
+        profImage = view.findViewById(R.id.ivProfileImage);
+        swipeContainer = (SwipeRefreshLayout) view.findViewById(R.id.swipeContainer);
+        /**profImage = new CircleImageView(getContext());
```
Comment (rfaisal) [inline app/src/main/java/com/example/solidarity/ProfileFragment.java:71]: No dead code please, especially without a comment.

**Review by rfaisal — APPROVED** [review]
